# The URL the site will be built for
base_url = "https://sohrabbehdani.ir/blog"

title = "Sohrab`s Free Contents"
description = "I share my ideas here :)"
default_language = "en"


#RSS
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

#Tags
taxonomies = [
    {name = "tags"}
]


theme = "terminimal"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "boron"


[extra]
accent_color = "green"
logo_text = "Sohrab Contents"
menu_items = [
    {name = "Blog", url = "$BASE_URL"},
    {name = "Tags", url = "$BASE_URL/tags"},
    {name = "Archives", url = "$BASE_URL/archive"},
    {name = "My Website", url = "https://sohrabbehdani.ir", newtab = true},
    {name = "Persian Blog", url = "https://blogfa.sohrabbehdani.ir", newtab = true},
]

copyright_html = "All posts in this blog are under the &nbsp; <b>CC-BY-SA</b>"


enable_post_view_navigation = true
post_view_navigation_prompt = "Thanks for reading! Read other posts?"
page_titles = "main_only"

