on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring Git user
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: checkout
        uses: actions/checkout@v4
      - name: Build Zola for GitHub Pages
        uses: kytta/zola-build-pages@v1.0.0    
        env:
          # Target branch
          PAGES_BRANCH: main
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
