on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        run: git config --global init.defaultBranch main
        env:
          # Target branch
          PAGES_BRANCH: main
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
